### ISSUE TITLE
Could not find a declaration file for module 'json2xlsx'.

### ISSUE THREAD

**Issue by THammami01** [BeAce/react-filedownload#1]
After installing the library in my React/TypeScript project, I get this error:

Could not find a declaration file for module 'json2xlsx. 'path/to/project/node_modules/json2xlsx/json2xlsx.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/json2xlsx` if it exists or add a new declaration (.d.ts) file containing `declare module 'json2xlsx';`

But no `@types/json2xlsx` in the Npm/Yarn registeries.
This is what I get when attempting to install the package with `yarn add -D @types/json2xlsx`:
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fjson2xlsx: Not found".

**Comment by Beace** [comment]
Sorry to bother you. In fact, this is a case to show how to generate xlsx files on the front end. You can refer to `example/index.js`,it is not necessary to install.

**Comment by THammami01** [comment]
Great. Thank you for the good work. 😊
